# Spring Boot configuration
spring:
  application:
    name: event-command-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-missing-locations: true

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.hostname}:5432/event_db
    username: eventmanager
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

# Postgres hostname
postgres:
  hostname: localhost

# Kafka outbox topic
event:
  outbox:
    topic: event_status

# Logger configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework: debug
    org.hibernate.stat: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Server configuration
server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# API Docs
springdoc:
  api-docs:
    path: /event-command-service/api-docs
  swagger-ui:
    path: /event-command-service/swagger-ui

# Monitoring
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always