# Spring Boot configuration
spring:
  application:
    name: ticket

  data:
    mongodb:
      database: ticket
      port: 27017
      host: localhost

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# API Docs
springdoc:
  api-docs:
    path: /api/v1/ticket/api-docs