# Spring Boot configuration
spring:
  application:
    name: ticket

  # Flyway migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: true
    baseline-on-migrate: true
    validate-on-migrate: false

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.hostname}:5432/event_ticket_db
    username: ticketmanager
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

# Postgres hostname
postgres:
  hostname: localhost

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate.stat: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Server configuration
server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

# API Docs
springdoc:
  api-docs:
    path: /api/v2/tickets/api-docs

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always