# Spring Boot configuration
spring:
  application:
    name: ticket
  data:
    mongodb:
      database: ${DB_NAME}
      port: %{MONGODB_PORT}
#      host: localhost

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug