spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: eureka
          uri: http://${eureka.instance.hostname}:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: eureka-static
          uri: http://${eureka.instance.hostname}:8761
          predicates:
          - Path=/eureka/**

        - id: event-query
          uri: lb://EVENT-QUERY
          predicates:
          - Path=/api/v2/events/**, /api/v2/event-query/**
          - Method=GET
        - id: event-command
          uri: lb://EVENT-COMMAND
          predicates:
          - Path=/api/v2/events/**
          - Method=POST, PUT, PATCH, DELETE
        - id: event-command-swagger
          uri: lb://EVENT-COMMAND
          predicates:
          - Path=/api/v2/event-command/**
          - Method=GET
        - id: ticket
          uri: lb://TICKET
          predicates:
          - Path=/api/v2/tickets/**, /api/v2/event/**
        - id: userprofile
          uri: lb://USERPROFILE
          predicates:
          - Path=/api/v2/user-profiles/**

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
