spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/**

        - id: event
          uri: lb://EVENT
          predicates:
          - Path=/api/v2/events/**
        - id: ticket
          uri: lb://TICKET
          predicates:
          - Path=/api/v2/tickets/**
          - Path=/api/v2/event/**
        - id: userprofile
          uri: lb://USERPROFILE
          predicates:
          - Path=/api/v2/user-profiles/**
        - id: swagger-ui-event
          uri: lb://EVENT/api/v2/events/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v2/events/(?<path>.*), /$\{path}
        - id: swagger-ui-ticket
          uri: lb://TICKET/api/v2/tickets/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**, /swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v2/tickets/(?<path>.*), /$\{path}
        - id: swagger-ui-user-profile
          uri: lb://USERPROFILE/api/v2/user-profiles/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**, /swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v2/user-profiles/(?<path>.*), /$\{path}


# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


