spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/**

        - id: event
          uri: lb://EVENT
          predicates:
          - Path=/api/v1/event/**
        - id: ticket
          uri: lb://TICKET
          predicates:
          - Path=/api/v1/ticket/**
        - id: swagger-ui-event
          uri: lb://EVENT/api/v1/event/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v1/event/(?<path>.*), /$\{path}
        - id: swagger-ui-ticket
          uri: lb://TICKET/api/v1/ticket/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**, /swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v1/ticket/(?<path>.*), /$\{path}


# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

