spring:
  application:
    name: userprofile

  flyway:
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userprofile_db
    username: userprofilemanager
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 8084
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# API Docs
springdoc:
  api-docs:
    path: /api/v2/user-profiles/docs