global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - eureka:8761
          - api-gateway:9000
          - event-query-service:8080
          - event-command-service:8081
          - ticket-service:8082
          - account-service:8084
          - notification-service:8085
          - event-indexer-service:8086
  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187
