spring:
  application:
    name: event-query-service

# ES Config
elasticsearch:
  hostname: localhost
  server: http://${elasticsearch.hostname}:9200
  user: event_query
  pass: elastic

# Server configuration
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# API Docs
springdoc:
  api-docs:
    path: /event-query-service/api-docs
  swagger-ui:
    path: /event-query-service/swagger-ui

# Monitoring
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: false

# Logger configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework: debug
