spring:
  application:
    name: event-query

# ES Config
elasticsearch:
  server: http://localhost:9200
  user: event_query
  pass: elastic

# Server configuration
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# API Docs
springdoc:
  api-docs:
    path: /api/v2/events/api-docs

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework: info
